#+Title: CatKit: Catalysis Kit
#+Author: SUNCAT Method Development Team
#+OPTIONS: toc:nil

#+BEGIN_HTML
<a href='https://travis-ci.org/SUNCAT-Center/CatKit.svg?branch=master'><img src='https://travis-ci.org/SUNCAT-Center/CatKit.svg?branch=master'/></a>
<a href='https://coveralls.io/github/SUNCAT-Center/CatKit?branch=master'><img src='https://coveralls.io/repos/github/SUNCAT-Center/CatKit/badge.svg?branch=master' alt='Coverage Status' /></a>
#+END_HTML

Welcome to CatKit! A staging ground for computational tools which are generally useful for catalysis research. The goal of the project is to provide a communal location for those interested in hosting such tools under a common banner. In doing so, we hope to provide the infrastructure to produce more advanced functionality based on modular components of individual contributors.

* Gratoms object
The =Gratoms= object is a child class of the ASE =Atoms= object class. Effectively, this means that it has all the same functionality as an =Atoms= object with some additional features as well.

TODO: I can haz documentation?

* CatGen: Catalysis Generator
CatGen is an enumeration module designed to construct various catalytic structures.

- [X] Gas phase molecules
- [ ] Bulk structures
- [X] Surfaces structures
- [X] Adsorption sites
- [X] Catalytic structures

It also has functionality for enumeration of other systems relevant to the field of catalysis.

- [X] Reaction mechanisms
- [X] Reaction routes

For additional details regarding how the generator operates, including example usage, see the [[./catgen/readme.org][CatGen readme]].

* Dependencies
CatKit attempts to make use of basic functionalities implemented by existing softwares when possible to extend its capabilities.

A full list of required packaged can be found in [[./requirements.txt]].
