#+Title: CatKit: Catalysis Kit
#+Author: SUNCAT Method Development Team
#+OPTIONS: toc:nil
#+LATEX_HEADER: \setlength{\parindent}{0em}

#+BEGIN_HTML
<a href='https://travis-ci.org/SUNCAT-Center/CatKit.svg?branch=master'><img src='https://travis-ci.org/SUNCAT-Center/CatKit.svg?branch=master'/></a>
<a href='https://coveralls.io/github/SUNCAT-Center/CatKit?branch=master'><img src='https://coveralls.io/repos/github/SUNCAT-Center/CatKit/badge.svg?branch=master' alt='Coverage Status' /></a>
<a href='http://catkit.readthedocs.io/en/latest/?badge=latest'><img src='https://readthedocs.org/projects/catkit/badge/?version=latest' alt='Documentation Status' /></a>
#+END_HTML

Welcome to CatKit! A staging ground for computational tools which are generally useful for catalysis research. The goal of the project is to provide a communal location for those interested in hosting such tools under a common banner. In doing so, we hope to provide the infrastructure to produce more advanced functionality based on modular components of individual contributors.

You can find our [[http://catkit.readthedocs.io/en/latest/?badge=latest][full documentation here]].

* Installation
** Pip installation
CatKit is most easily installed with pip using:

#+BEGIN_SRC sh
pip install catkit
#+END_SRC

For Mac OSX, homebrew can be used in place of pip

#+BEGIN_SRC sh
brew install catkit
#+END_SRC

For usage on high-performance computers, installation will need to be performed locally which can be done using:

#+BEGIN_SRC sh
pip install --user catkit
#+END_SRC

These commands will install all of the necessary dependencies for you. 

** Source installation
Alternatively, a version with the most recent commits can be install through git by running the following in your home directory.

#+BEGIN_SRC sh
git clone https://github.com/SUNCAT-Center/CatKit.git catkit
#+END_SRC

Then, add =~/catkit= to your =PYTHONPATH= by adding the following line to your =~/.bashrc= file.

#+BEGIN_SRC sh
export PYTHONPATH=~/catkit:$PYTHONPATH
#+END_SRC

Or, one can use pip to install from the master branch directly:

#+BEGIN_SRC sh
pip install --upgrade git+https://github.com/SUNCAT-Center/CatKit.git catkit
#+END_SRC

To properly install the =cathub= command line interface, you will also need to run the =setup.py=. This can be done by performing a pip installation as developer in the catkit directory.

#+BEGIN_SRC sh
cd ~/cakit
pip install -e .
#+END_SRC

* CatGen: Catalysis Generator
CatGen is an enumeration module designed to construct various catalytic structures.

- [X] Gas phase molecules
- [ ] Bulk structures
- [X] Surfaces structures
- [X] Adsorption sites
- [X] Catalytic structures

It also has functionality for enumeration of other systems relevant to the field of catalysis.

- [X] Reaction mechanisms
- [X] Reaction routes

For additional details regarding how the generator operates, including example usage, see the [[https://catkit-jboes.readthedocs.io/en/latest/_static/frontmatter/catgen.html][CatGen documentation]].

* CatHub: Catalysis-Hub.org
CatHub provides an interface to the reaction energy database on [[http://www.catalysis-hub.org][Catalysis-Hub.org]].

The module includes a command line interface that can be used to access and upload to the database:

Run `cathub`:

- cathub --help

See the [[https://catkit-jboes.readthedocs.io/en/latest/_static/frontmatter/cathub.html][CatHub documentation]] for details on how to use the cli.

* CatFlow: Catalysis Workflow
CatFlow is currently a staging ground for Workflow code and techniques. These functions are meant to be used in conjunction with the other modules inside CatKit to help automate these tasks.

Currently, CatFlow's functionality utilizes [[https://materialsproject.github.io/fireworks/][Fireworks]] and many of the functions are also specifically tailored to work on the high-performance computers which are available to the [[http://suncat.stanford.edu/][SUNCAT]] group as Stanford.

For additional detail see the [[https://catkit-jboes.readthedocs.io/en/latest/_static/frontmatter/catflow.html][CatFlow documentation]].

* Dependencies
CatKit attempts to make use of basic functionalities implemented by existing softwares when possible to extend its capabilities.

A full list of required packaged can be found in [[./requirements.txt][the requirements]].
