#+Title: CatKit: Catalysis Kit
#+Author: SUNCAT Method Development Team
#+OPTIONS: toc:nil
#+LATEX_HEADER: \setlength{\parindent}{0em}

#+BEGIN_HTML
<a href='https://travis-ci.org/SUNCAT-Center/CatKit.svg?branch=master'><img src='https://travis-ci.org/SUNCAT-Center/CatKit.svg?branch=master'/></a>
<a href='https://coveralls.io/github/SUNCAT-Center/CatKit?branch=master'><img src='https://coveralls.io/repos/github/SUNCAT-Center/CatKit/badge.svg?branch=master' alt='Coverage Status' /></a>
<a href='http://catkit.readthedocs.io/en/latest/?badge=latest'><img src='https://readthedocs.org/projects/catkit/badge/?version=latest' alt='Documentation Status' /></a>
#+END_HTML

Welcome to CatKit! A staging ground for computational tools which are generally useful for catalysis research. The goal of the project is to provide a communal location for those interested in hosting such tools under a common banner. In doing so, we hope to provide the infrastructure to produce more advanced functionality based on modular components of individual contributors.

* CatGen: Catalysis Generator
CatGen is an enumeration module designed to construct various catalytic structures.

- [X] Gas phase molecules
- [ ] Bulk structures
- [X] Surfaces structures
- [X] Adsorption sites
- [X] Catalytic structures

It also has functionality for enumeration of other systems relevant to the field of catalysis.

- [X] Reaction mechanisms
- [X] Reaction routes

For additional details regarding how the generator operates, including example usage, see the [[./docs/catkit/gen/gen.org][CatGen documentation]].

* CatFlow: Catalysis Workflow
CatFlow is currently a staging ground for Workflow code and techniques. These functions are meant to be used in conjunction with the other modules inside CatKit to help automate these tasks.

Currently, CatFlow's functionality utilizes [[https://materialsproject.github.io/fireworks/][Fireworks]] and many of the functions are also specifically tailored to work on the high-performance computers which are available to the [[http://suncat.stanford.edu/][SUNCAT]] group as Stanford.

For additional detail see the [[./docs/catkit/flow/flow.org][CatFlow documentation]].

* CatHUB: Catalysis Hub
Coming soon.

* Dependencies
CatKit attempts to make use of basic functionalities implemented by existing softwares when possible to extend its capabilities.

A full list of required packaged can be found in [[./requirements.txt][the requirements]].
