#+TITLE: Catalysis Kit
#+LANGUAGE: en
#+OPTIONS:   H:4 num:nil toc:2
#+AUTHOR: Jacob Boes
#+EMAIL: mailto:jacobboes@gmail.com

#+SETUPFILE: /home/jboes/scripts/org-html-themes/setup/theme-bigblow.setup


* Catalysis Kit

Catalysis Kit (CatKit) modules for setting up, manipulating, running, visualizing and analyzing atomistic simulations.  The code is freely available under the [[../LICENSE][GPLv3]].

** CatGen: Catalysis Generator
CatGen is an enumeration module designed to construct various catalytic structures.

- [X] Gas phase molecules
- [ ] Bulk structures
- [X] Surfaces structures
- [X] Adsorption sites
- [X] Catalytic structures

It also has functionality for enumeration of other systems relevant to the field of catalysis.

- [X] Reaction mechanisms
- [X] Reaction routes

** CatFlow: Catalysis Workflow
CatFlow is currently a staging ground for Workflow code and techniques. These functions are meant to be used in conjunction with the other modules inside CatKit to help automate these tasks.

Currently, CatFlow's functionality utilizes [[https://materialsproject.github.io/fireworks/][Fireworks]] and many of the functions are also specifically tailored to work on the high-performance computers which are available to the [[http://suncat.stanford.edu/][SUNCAT]] group as Stanford.

** CatHUB: Catalysis Hub
Coming soon.
